version: '3.4'
services:
  php-fpm:
    build:
      context: docker/php
    container_name: skeleton_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ~/.composer:/.composer
    networks:
      - network_skeleton
  nginx:
    container_name: skeleton_nginx
    build:
      dockerfile: docker/nginx/Dockerfile
      context: .
      target: basic
    working_dir: /var/www/html
    volumes:
      - ./public:/var/www/html
    ports:
      - ${API_PORT}:80
    networks:
      - network_skeleton
  adminer:
    image: adminer:latest
    container_name: skeleton_adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - network_skeleton
  postgres:
    image: postgres:11.1-alpine
    container_name: skeleton_postgres
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - network_skeleton

networks:
  network_skeleton:
    driver: bridge