version: '3.4'
services:
  php:
    build:
      context: docker/php
    container_name: skeleton_php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ~/.composer:/.composer
    networks:
      - network_ske
  adminer:
    image: adminer:latest
    container_name: skeleton_adminer
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - network_ske
  postgres:
    image: postgres:11.1-alpine
    container_name: skeleton_postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - network_ske

networks:
  network_ske:
    driver: bridge