services:
  command.env.database:
    class: AdnanMula\Skeleton\Entrypoint\Command\CreateDatabaseCommand
    arguments:
      - '@repository.dbal.connection'
    tags:
      - { name: console.command, command: 'skeleton:env:database' }

  command.env.migrations:
    class: AdnanMula\Skeleton\Entrypoint\Command\LoadMigrationsCommand
    arguments:
      - '@AdnanMula\Skeleton\Infrastructure\Migrations\MigrationsRegistry'
    tags:
      - { name: console.command, command: 'skeleton:env:migrations' }

  command.env.fixtures:
    class: AdnanMula\Skeleton\Entrypoint\Command\LoadFixturesCommand
    arguments:
      - '@AdnanMula\Skeleton\Infrastructure\Fixtures\FixturesRegistry'
      - '@repository.dbal.connection'
    tags:
      - { name: console.command, command: 'skeleton:env:fixtures' }