services:
  command.env.init:
    class: AdnanMula\Skeleton\Entrypoint\Command\InitEnvironmentCommand
    arguments:
      - '@repository.dbal.migration.v001'
    tags:
      - { name: console.command, command: 'skeleton:env:init' }

  command.env.fixtures:
    class: AdnanMula\Skeleton\Entrypoint\Command\LoadFixturesCommand
    arguments:
      - '@AdnanMula\Skeleton\Infrastructure\Fixtures\FixturesRegistry'
      - '@repository.dbal.connection'
    tags:
      - { name: console.command, command: 'skeleton:env:fixtures' }