parameters:
    db_url: '%env(resolve:DATABASE_URL)%'

services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: false

    AdnanMula\Skeleton\Application\:
        autowire: true
        autoconfigure: true
        resource: '../src/Application/*/*/*Handler.php'
        tags: [{ name: messenger.message_handler, bus: messenger.bus.command }]

    AdnanMula\Skeleton\Domain\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Domain/Service'

    AdnanMula\Skeleton\Infrastructure\Service\:
        autowire: true
        autoconfigure: true
        resource: '../src/Infrastructure/Service'

    AdnanMula\Skeleton\Infrastructure\Persistence\Repository\:
        autowire: true
        autoconfigure: true
        resource: '../src/Infrastructure/Persistence/Repository'

#    AdnanMula\Skeleton\Migrations\:
#        autowire: true
#        autoconfigure: true
#        resource: '../migrations'

    AdnanMula\Skeleton\Infrastructure\Fixtures\FixturesRegistry:
        class: AdnanMula\Skeleton\Infrastructure\Fixtures\FixturesRegistry

    AdnanMula\Skeleton\Infrastructure\Fixtures\:
        autoconfigure: true
        autowire: true
        resource: '../src/Infrastructure/Fixtures/*/*'
        tags: ['skeleton.fixture']

imports:
    - { resource: context/system/buses.yaml }
    - { resource: context/system/repositories.yaml }
    - { resource: context/system/commands.yaml }
    - { resource: context/user/repositories.yaml }
